<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages\Class;

class QuerystringGenerated extends \Fusion\FusionPage
{
    #[\Fusion\Attributes\SyncQueryString]
    public string $name = 'Aaron';
}