<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages\Class;

use Fusion\Attributes\IsReadOnly;
class ReadOnlyGenerated extends \Fusion\FusionPage
{
    #[IsReadOnly]
    public string $value = 'Cant change me!';
}