<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages\Class;

class SimpleFunctionGenerated extends \Fusion\FusionPage
{
    public function mount()
    {
        //
    }
    public function favorite()
    {
        return 'favorite worked';
    }
}