<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages\Class;

use Fusion\Attributes\IsReadOnly;
class SyncStateGenerated extends \Fusion\FusionPage
{
    public string $name = 'Aaron';
    #[IsReadOnly]
    public string $computed = '';
    public function mount()
    {
        $this->computed = 'Name is: ' . $this->name;
    }
}