<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages;

class FunctionStateGenerated extends \Fusion\FusionPage
{
    public function hello()
    {
        sleep(1);
    }
}