<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages;

use Symfony\Component\Finder\Finder;
class IndexGenerated extends \Fusion\FusionPage
{
    #[\Fusion\Attributes\ServerOnly]
    public array $discoveredProps = ['files'];
    use \Fusion\Concerns\IsProceduralPage;
    public function runProceduralCode()
    {
        $files = (new Finder())->files()->in(config('fusion.paths.pages'))->name('*.vue');
        $files = collect($files)->map(function ($file) {
            return str($file->getRelativePathname())->chopEnd('.vue')->lower();
        });
        $this->prop(name: 'files', default: $files)->value();
        $this->syncProps(get_defined_vars());
    }
}