<script>
  /*
   * This file is automatically generated by the fusion:shim
   * Laravel command. You should not need to edit it.
   */
  // [insert:head]

  // [insert:keys]

  /**
   * You should not need to pass any props to this function, the
   * Fusion Vite plugin should automatically inject them.
   *
   * // [insert:params]
   * // [insert:returns]
   */
  export function useFusion(props = {}) {
    // [insert:props]

    // [insert:methods]

    // [insert:exports]
  }
</script>