<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages\Class\Basic;

class OptionsNoSetupGenerated extends \Fusion\FusionPage
{
    public string $name = 'Aaron';
}