<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages\Imports;

class OptionsWithSetupGenerated extends \Fusion\FusionPage
{
    public string $fname = 'Aaron';
    public string $lname = 'Francis';
}