<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages;

class FusionSyncNotPresentGenerated extends \Fusion\FusionPage
{
    //
}