<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages;

class FusionPresentGenerated extends \Fusion\FusionPage
{
    public string $name = 'Aaron';
}