<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages\Procedural;

class ReadOnlyGenerated extends \Fusion\FusionPage
{
    #[\Fusion\Attributes\ServerOnly]
    public array $discoveredProps = ['value'];
    use \Fusion\Concerns\IsProceduralPage;
    public function runProceduralCode()
    {
        $value = $this->prop(name: 'value', default: 'Cant change me!')->readonly()->value();
        $this->syncProps(get_defined_vars());
    }
}