<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages\Procedural;

class SimpleFunctionGenerated extends \Fusion\FusionPage
{
    use \Fusion\Concerns\IsProceduralPage;
    public function runProceduralCode()
    {
        $this->expose(favorite: function () {
            return 'favorite worked';
        });
        $this->syncProps(get_defined_vars());
    }
    #[\Fusion\Attributes\Expose]
    public function favorite()
    {
        return call_user_func($this->actions[__FUNCTION__], ...func_get_args());
    }
}