<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages\Procedural;

class SyncStateGenerated extends \Fusion\FusionPage
{
    #[\Fusion\Attributes\ServerOnly]
    public array $discoveredProps = ['name', 'computed'];
    use \Fusion\Concerns\IsProceduralPage;
    public function runProceduralCode()
    {
        $name = $this->prop(name: 'name', default: 'Aaron')->value();
        $computed = $this->prop(name: 'computed', default: fn() => "Name is: {$name}")->readonly()->value();
        $this->syncProps(get_defined_vars());
    }
}